"""What the companion can say, in the two languages it speaks.

A table and nothing else: no Qt, no I/O, no decisions. It lives apart from the
companion because the process that draws a character and the sentences it
reads out have no reason to change together, and because a test that checks
the table against the signals should not have to start a UI to do it.

Four rules the table has to keep, all four pinned by tests:

  - every category exists in "en" and "pt" with the same number of lines, or
    the shallower language repeats itself more often for no reason;
  - eight lines per category, because two lines in rotation is one line — the
    version before this said "ti finished" for an hour straight;
  - at most three lines in a category may be built as "clause. clause." The
    whole table used to be that shape, and a form repeated a hundred and
    thirty-nine times stops being a style and becomes a stutter. The rest have
    to be something else: one sentence, a question aimed at the person, a
    short reaction, a long sentence that breathes, or one that opens with a
    verb. tests/test_buddy_lines.py counts them;
  - the range of lengths gets used. A ceiling of 150 with every line at 100 is
    the same monotony measured against a different number, so each category
    carries at least one short line and at least one long one.

The register is second person. It talks *to* the person whose machine it lives
on: it can say hello, ask a question, or remark on what they are doing. That
inverts the rule the earlier version of this file and buddy_voice.SYSTEM both
stated ("never greet"), and the greeting category exists precisely because a
mascot that appears on a desktop and says nothing about arriving is furniture.

Registers are mixed inside every category on purpose, because one register for
thirty categories is the defect above wearing different words: a line that
carries a number and says what it means, a line that teaches something a
programmer would recognise, a line with a specific reference rather than vague
irony, and a line with a concrete thought about programming, waiting or the
cost of a decision. Nothing that would fit on a mug: a remark about finitude,
time or the fate of man says nothing about this desktop and could have been
written before the machine was switched on.

Every placeholder in a line has to be supplied by the signal that selects the
category (see buddy_signals.PRIORITY). A line with a placeholder nothing fills
prints the braces on screen; a category no signal names is dead text, which is
what happened to "twoRed" for as long as nothing read the rate limits.

Lines are at most 150 characters — the same ceiling buddy_voice.MAX_CHARS puts
on the model-written ones, so written and generated lines fit the same bubble.
The bubble word-wraps inside a fixed width and grows downwards, so the ceiling
is about how long a person will stand there reading, not about pixels.
"""


# What it can say. Eight lines per trigger, because two lines in rotation is
# the same line: the previous version said "ti finished" for an hour straight.
#
# Categories beyond the alerts exist so that a quiet system still produces
# variety — a companion with nothing to say and no idle repertoire either says
# the same alert forever or goes mute.
#
# "en" and "pt" are written separately rather than translated. A joke that
# survives translation is usually the one that was not doing much work.
LINES = {
    "en": {
        "greeting": [
            "Hello again.",
            "I am up and reading your quotas — say the word and I go back to being furniture.",
            "What are we breaking today?",
            "Booted. Nothing is on fire yet, which I will take as a good sign.",
            "A purple mascot with opinions about your rate limits: the nineties called and I let it ring.",
            "Good to see you.",
            "I read sessions.json and widget-data.json every few seconds, so anything I say about your usage came from a file you can open.",
            "You left me running. That is either trust or forgetfulness.",
        ],
        "background": [
            "{name} says done; {n} still running.",
            "Do not close {name}'s terminal.",
            "{name} called the turn finished while {n} of its own agents are still working, so what you are reading is not the whole answer yet.",
            "Killing {name}'s parent shell takes those {n} background agents with it.",
            "{name} looks finished and is not. {n} still out there.",
            "Did you look at what those {n} agents are doing in {name}?",
            "{n} things running in {name} with nobody watching them.",
            "The turn ended in {name}. The work did not.",
        ],
        "allQuiet": [
            "{name} is finished, session and background both.",
            "That is {name} finished.",
            "{name} stopped {idle} ago and nothing it started is still alive, which is the only version of finished that counts for anything.",
            "Anything left to check in {name}?",
            "{name} closed the loop. Rare enough to mention.",
            "No turn, no agents, no children: {name} is quiet all the way down.",
            "Nothing has moved in {name} for {idle}.",
            "{name} is done on both sides. The session and the work it left running.",
        ],
        "asking": [
            "{name} is waiting on you.",
            "Go answer {name}.",
            "{name} stopped mid-task to ask something and will sit there until a person types an answer, because it has nowhere else to be.",
            "Did you see that {name} is asking?",
            "{name} has a question. Its patience is infinite and unhelpful.",
            "A prompt with nobody in front of it is {name} holding a lock on your attention.",
            "{name} needs a decision from you, not from me.",
            "{name} is blocked on input. That is the one thing autonomy cannot do for you.",
        ],
        "waiting": [
            "{name} finished {idle} ago.",
            "Go look at {name}.",
            "The turn in {name} ended {idle} ago and nothing has read the diff since, which is the part that decides whether any of it was worth it.",
            "Did {name} do what you asked, or what you typed?",
            "{name} delivered. Confidence is not a review.",
            "Reviewing what {name} did is the step people skip when the output looks sure of itself.",
            "{name}: done {idle} ago, still unread.",
            "{name} wrapped up and is idling. Your move.",
        ],
        "idle": [
            "{name} has been still for {idle}, with an agent of its own still running somewhere.",
            "{name}: quiet, not finished.",
            "Something {name} started {idle} ago is still going, and the session has nothing to say about it, because background work reports to nobody.",
            "Is {name} waiting for you or for itself?",
            "{name} idles while its own subprocess works. Delegation, of a sort.",
            "Quiet for {idle} is not the same as done while a child of {name} still holds the file.",
            "{name} stopped. What it launched did not.",
            "A parent that exits before its children is how orphans reach init, and {name} has not exited yet.",
        ],
        "twoRed": [
            "{a} and {b} are both past ninety percent. This is fine.",
            "Two windows in the red at once.",
            "{a} and {b} are both over ninety percent used, which means there is no window left to move the work into when one of them closes.",
            "Both of them, same afternoon.",
            "When {a} and {b} go red together, the fallback is a clock rather than another model.",
            "Which one do you think resets first, {a} or {b}?",
            "{a} red, {b} red, nothing left to borrow from.",
            "Burning two limits at the same time takes a certain kind of commitment.",
        ],
        "compaction": [
            "{n} compactions today.",
            "Each one is a lossy summary of the last one.",
            "Compaction rewrote your context {n} times today, and a summary of a summary is how detail leaves without anyone deciding to drop it.",
            "{n} compactions. Ship of Theseus, with worse documentation.",
            "Do you still know what this session originally asked for?",
            "{n} times the window filled up: smaller questions are allowed.",
            "Split the task and the context stops eating itself.",
            "{n} rewrites of the same memory, each one shorter than the one before.",
        ],
        "readRatio": [
            "{n}:1, read to written.",
            "Reading a library to write a postcard.",
            "For every token this writes, {n} go in, and you pay the reading side of that ratio on every turn after the one that opened the file.",
            "{n} tokens in, one out. Efficient is not the word.",
            "Does it need the whole file, or the forty lines around the bug?",
            "Input is cheaper than output per token, which is exactly why {n}:1 stops looking alarming and starts looking like a habit.",
            "{n}:1 — most of that context is along for the ride.",
            "Point it at a range instead of a file.",
        ],
        "bashHeavy": [
            "{n}% of your calls are Bash.",
            "The other tools are right there.",
            "{n}% of every tool call today was a shell command, which works until one of them is not idempotent and the retry runs it twice.",
            "{n}% Bash. There are other tools, allegedly.",
            "Is grep faster here, or just more familiar?",
            "A shell command has no schema, so nothing checks it before it runs.",
            "{n}% shell: a philosophy, of sorts.",
            "When the hammer has a pipe in it, everything looks like a pipeline.",
        ],
        "cacheDrop": [
            "Cache hit at {n}%.",
            "Something is invalidating the prefix.",
            "The cache matches on an exact prefix, so one changed byte near the front of the prompt misses everything after it, and yours is at {n}%.",
            "{n}% cache hit. A timestamp in the system prompt would do that.",
            "What did you add to the top of the prompt today?",
            "Prefix caching is all or nothing per block: {n}% means most blocks are being rebuilt.",
            "{n}% is paid for in latency before it is paid for in tokens.",
            "Move the volatile part to the end of the prompt.",
        ],
        "nightOwl": [
            "It is late.",
            "The commit will still be broken tomorrow.",
            "Past midnight the bug you are chasing is a typo more often than it is a race condition, and you are the wrong person to tell them apart.",
            "Late. Nothing good gets merged at this hour.",
            "One more, then bed?",
            "Tomorrow-you reads this code as a stranger, and the stranger has no context window.",
            "The night shift writes the code the morning shift reverts.",
            "Go to sleep.",
        ],
        "sessionSpread": [
            "{n} sessions running.",
            "Someone is going to lose track of this.",
            "There are {n} sessions open at once, each holding half an idea only you can tell apart, including whatever {name} was originally for.",
            "{n} at once. Impressive, or a diagnosis.",
            "Quick: what is {name} doing right now?",
            "Switching contexts costs more than the switch, because it costs the reload.",
            "{n} Claudes, one you.",
            "Close the two you have already forgotten about.",
        ],
        "quotaHigh": [
            "Session window at {n}%.",
            "{n}% of the five-hour window is gone, and the window is not interested in what you still had planned for it.",
            "At {n}% the fifth that is left is about one long turn plus the reading of what it returns.",
            "How much of that {n}% was re-reading the same file?",
            "{n}% used. The last fifth always goes faster than the first.",
            "Budget the questions from here.",
            "A window at {n}% is not a warning, it is arithmetic: what is left is what is left.",
            "{n}%, and the day is not over.",
        ],
        "quotaCritical": [
            "{n}% of the session window.",
            "Finish the thought.",
            "At {n}% the next long turn is the one that gets cut in the middle, and a cut turn spends the tokens without leaving you the answer.",
            "{n}% gone. Whatever you were saving it for, this is it.",
            "Is there anything here that has to happen inside this window?",
            "There is no plan B inside the same five hours.",
            "{n}% used, and no second window to fail over to.",
            "Write the state somewhere a restart can read it.",
        ],
        "weeklyHigh": [
            "Weekly window at {n}%.",
            "{n}% of the week is spent and the reset has a date, which is not the same as having a plan for the days between now and then.",
            "Days left, quota not.",
            "{n}% spent: the rest of the week runs on the remainder.",
            "{n}% of the weekly allowance. The calendar does not negotiate.",
            "Which of this week's jobs actually needed the big model?",
            "A weekly ceiling turns every busy Tuesday into a smaller Friday.",
            "Spread it, or spend it and wait.",
        ],
        "limitSoon": [
            "{eta} left at this pace.",
            "Nothing you start now is safe.",
            "At the current burn the limit lands in {eta}, which is less than one long turn plus the time it takes to read what it returns.",
            "{eta} to the ceiling. Choose the next question well.",
            "Do you want the last {eta} going to this, or to the thing you came here for?",
            "Write down where you are before the window closes.",
            "An estimate from the current rate is a straight line drawn through a jagged one.",
            "{eta} of quota, and after that it is a clock instead of a decision.",
        ],
        "creditsLow": [
            "{v} of extra credit left.",
            "After that, the answer is no.",
            "Extra usage was the fallback and {v} is what is left of the fallback, so the next long turn is the one that spends the end of it.",
            "Credit at {v}. The ceiling stops being theoretical.",
            "Do you want the rest of {v} going to this, or to tomorrow?",
            "Check the balance before a long turn rather than during one.",
            "{v} is a balance, not a rate — it says nothing about how fast it is leaving.",
            "The plan B has {v} of plan B left in it.",
        ],
        "incident": [
            "Anthropic is reporting {what}.",
            "Not your code, for once.",
            "The status page says {what}, which means the retry loop you were about to write has already been written by someone upstream.",
            "They are calling it {what}. Retrying angrily does not fix someone else's server.",
            "Want to go read something while this clears?",
            "Open incident: {what}.",
            "An overloaded error is the server saying it is full, not the client saying it is wrong.",
            "Upstream, and the name they gave it is: {what}.",
        ],
        "mcpAuth": [
            "{name} is waiting to be authorised.",
            "Until then it is decoration.",
            "The MCP server {name} is connected but not authorised, so its tools are missing from the list and nothing announces that they are missing.",
            "{name} wants credentials. It has been asking without an audience.",
            "Do you still use {name}, or does it only exist in the config?",
            "Run /mcp and give {name} its token.",
            "A tool that is not in the list is a tool the model will not think of.",
            "{name}: authorised nowhere, listed everywhere.",
        ],
        "errorsClimbing": [
            "{n} API errors in two hours.",
            "The retries are eating your turns.",
            "There were {n} failed calls in the last two hours, and every retry that hides one of them charges you the wait twice without saying so.",
            "{n} errors and climbing. The retry hides it until it stops hiding it.",
            "Does it feel slow, or does it feel broken?",
            "Exponential backoff turns a spike into a queue, which is why nothing looks wrong.",
            "{n} errors since the last quiet stretch, and not all of them are yours.",
            "Stop blaming the prompt for {n} network failures.",
        ],
        "opusFallback": [
            "Opus is {n}% of today's calls.",
            "Read the answers twice.",
            "Opus dropped to {n}% of today against a much heavier week, which usually means something smaller has been answering in its voice.",
            "{n}% Opus today. Nobody announced the change.",
            "Did you switch models, or did something switch for you?",
            "A model swap shows up in the output before it shows up in the settings.",
            "{n}% Opus: the mix moved and the prompts did not.",
            "Check which model is answering before you rewrite the prompt.",
        ],
        "slowResponses": [
            "Answers averaging {n} seconds.",
            "Long enough to lose the thread.",
            "Round trips of {n} seconds are long enough that you start a second task, and what that costs is the context in your head, not the one in the window.",
            "{n} seconds a turn. That is not the model thinking harder.",
            "Have you got something to read while this comes back?",
            "Latency is measured per call; the wait you feel is per turn, and a turn is several calls.",
            "{n} seconds each, and the average is hiding the worst of them.",
            "{n}s round trips. Patience became a dependency.",
        ],
        "expensiveSession": [
            "{name} is ${usd} of today.",
            "One repository, most of the bill.",
            "{name} accounts for ${usd} today, more than half of everything, so whatever it was doing it was doing at full price.",
            "${usd} in {name}. Hope it was load-bearing.",
            "Was {name} worth ${usd} to you, or only to the loop?",
            "Cost concentrates where the context is largest, not where the work is hardest.",
            "{name}: ${usd}, and the day is not over.",
            "Split the long session before it splits the budget.",
        ],
        "runwayShort": [
            "About {h}h of credit at this burn.",
            "After that it stops being your decision.",
            "The projection divides what is left by what you have been spending per hour, so {h}h is a straight line drawn through a very jagged afternoon.",
            "{h}h of runway. The rate is the part you can still change.",
            "Would you rather run out of credit before dinner or after?",
            "Spending faster does not extend {h}h.",
            "{h}h left, and a queue of long turns is the fastest way to make it fewer.",
            "Runway is balance over burn: halve the burn and it doubles.",
        ],
        "recordSession": [
            "{h}h in one session.",
            "Close to your longest ever.",
            "This session has been open for {h} hours, which is long enough that the beginning of it has already been compacted out of the middle.",
            "{h}h and still open. Context has a half-life.",
            "Do you remember what the first message in this one asked for?",
            "A record like that measures the session rather than the work.",
            "Long sessions do not accumulate understanding, they accumulate summary.",
            "Start a new one and paste in the three things that matter.",
        ],
        "branchOpinion": [
            "{name} is on {branch}.",
            "Branches are cheap; this one is not.",
            "You are committing straight to {branch} in {name}, where every commit is immediately everyone's and the undo is a revert with your name on it.",
            "{branch} in {name}. Bold, in the historical sense.",
            "Would you approve this diff if someone else had pushed it to {branch}?",
            "A branch is a name for a commit, and making one costs a pointer.",
            "{name} on {branch}, with no cheap way back.",
            "Branch first, then be brave.",
        ],
        "streakDay": [
            "{n} days in a row.",
            "The log noticed before you did.",
            "That is {n} consecutive days with something recorded, which says more about the habit than about any one of the days inside it.",
            "Day {n}. Nobody is counting except the log.",
            "Is this a streak, or a schedule you did not agree to?",
            "Streaks end on the day you start defending them.",
            "{n} days unbroken, and the counter has no opinion about the code.",
            "Take a day off and see whether it survives.",
        ],
        "offPeak": [
            "Not one of your hours.",
            "Your own history says you are usually somewhere else right now.",
            "This hour sits outside the block your own log calls the working day, and odd hours are where the commits nobody remembers writing come from.",
            "An odd hour for you. Something did not wait.",
            "Did this have to happen now?",
            "The histogram of your last few weeks has no bar here.",
            "Off your usual hours, by your own data rather than my opinion.",
            "Whatever this is, it will still be here at ten.",
        ],
        "ambient": [
            "All quiet.",
            "Nothing needs you, which is a state worth noticing while it lasts.",
            "No alerts, no questions, nothing in the red — the whole board is dull and I have checked it twice.",
            "Everything is fine. Suspiciously fine.",
            "Enjoying the quiet, or looking for something to break?",
            "Nothing to report.",
            "Machines behaving. Deeply uneventful.",
            "Still here, still watching, still nothing.",
        ],
        "philosophy": [
            "You are the slowest part of this loop and the only part that decides anything.",
            "Reading code is harder than writing it, which is why so much of it gets rewritten instead of read.",
            "It will finish. Whether it finishes what you meant is a different question.",
            "A four-second wait is a pause; a forty-second wait is a context switch.",
            "Every prompt is a guess about which forty lines of the repository matter, and most of the cost is in guessing wide.",
            "Automating the work does not remove it. It moves you from doing it to reviewing it.",
            "Nobody meters attention.",
            "The expensive part was never the answer, it is deciding whether the answer is right.",
        ],
    },
    "pt": {
        "greeting": [
            "Voltei.",
            "Subi aqui. Nada pegando fogo por enquanto.",
            "O que a gente quebra hoje?",
            "Sou um mascote roxo com opinião sobre a sua cota; a parte do adware ficou nos anos 2000.",
            "Leio o sessions.json e o widget-data.json a cada poucos segundos, então tudo que eu falar de uso saiu de um arquivo que você pode abrir.",
            "Bom te ver.",
            "Me deixou rodando de novo. Ou é confiança, ou é esquecimento.",
            "Estou de olho nas suas janelas de cinco horas e de sete dias, e vou comentar sem você pedir.",
        ],
        "background": [
            "{name} diz que acabou; {n} ainda rodando.",
            "Não fecha o terminal do {name}.",
            "O {name} deu o turno por encerrado com {n} agentes dele ainda trabalhando, então o que você está lendo ainda não é a resposta inteira.",
            "Matar o shell pai do {name} leva junto esses {n} agentes.",
            "{name} parece pronto e não está. Tem {n} lá fora.",
            "Você viu o que esses {n} agentes estão fazendo no {name}?",
            "{n} coisas rodando no {name} sem ninguém olhando.",
            "O turno acabou no {name}. O trabalho não.",
        ],
        "allQuiet": [
            "{name} terminou de verdade: a sessão e o que ela largou rodando.",
            "O {name} acabou.",
            "O {name} parou faz {idle} e nada que ele começou continua vivo, que é a única versão de terminado que vale alguma coisa.",
            "Sobrou algo pra conferir no {name}?",
            "{name} fechou o ciclo. Raro o bastante pra comentar.",
            "Sem turno, sem agente, sem processo filho: o {name} está quieto até embaixo.",
            "Nada se mexe no {name} há {idle}.",
            "{name} está pronto dos dois lados. O da sessão e o do que rodava atrás.",
        ],
        "asking": [
            "{name} está esperando por você.",
            "Vai responder o {name}.",
            "O {name} parou no meio pra perguntar uma coisa e vai ficar ali até alguém digitar a resposta, porque ele não tem outro lugar pra ir.",
            "Você viu que o {name} perguntou?",
            "{name} tem uma pergunta. A paciência dele é infinita e inútil.",
            "Um prompt sem humano na frente é o {name} segurando um lock na sua atenção.",
            "{name} precisa de uma decisão sua, não minha.",
            "{name} travado no input. É a única coisa que a autonomia não faz por você.",
        ],
        "waiting": [
            "{name} terminou faz {idle}.",
            "Vai olhar o {name}.",
            "O turno do {name} fechou faz {idle} e ninguém leu o diff desde então, que é justamente a parte que decide se aquilo valeu alguma coisa.",
            "O {name} fez o que você pediu ou o que você escreveu?",
            "{name} entregou. Confiança não é revisão.",
            "Revisar o que o {name} fez é o passo que todo mundo pula quando a saída parece segura de si.",
            "{name}: pronto faz {idle}, e ainda sem leitor.",
            "{name} acabou e está de bobeira. É sua vez.",
        ],
        "idle": [
            "{name} está parado há {idle}, com um agente dele ainda rodando em algum canto.",
            "{name}: quieto, não pronto.",
            "Alguma coisa que o {name} começou faz {idle} continua rodando, e a sessão não tem nada a dizer sobre isso, porque background não presta contas.",
            "O {name} está esperando você ou esperando ele mesmo?",
            "{name} ocioso enquanto o subprocesso dele trabalha. Delegação, de certo modo.",
            "Quieto há {idle} não é o mesmo que terminado enquanto um filho do {name} ainda segura o arquivo.",
            "{name} parou. O que ele lançou, não.",
            "Pai que sai antes dos filhos é como órfão vira problema do init, e o {name} nem saiu ainda.",
        ],
        "twoRed": [
            "{a} e {b} passaram dos noventa por cento. This is fine.",
            "Duas janelas no vermelho ao mesmo tempo.",
            "{a} e {b} estão os dois acima de noventa por cento, ou seja, não sobrou janela nenhuma pra onde empurrar o trabalho quando uma fechar.",
            "As duas, na mesma tarde.",
            "Quando {a} e {b} ficam vermelhos juntos, o plano B é um relógio e não outro modelo.",
            "Qual você acha que reseta primeiro, {a} ou {b}?",
            "{a} no vermelho, {b} no vermelho, nada pra pegar emprestado.",
            "Queimar dois limites ao mesmo tempo exige um certo tipo de dedicação.",
        ],
        "compaction": [
            "{n} compactações hoje.",
            "Cada uma é um resumo com perda do resumo anterior.",
            "A compactação reescreveu seu contexto {n} vezes hoje, e resumo de resumo é como o detalhe some sem ninguém ter decidido jogar ele fora.",
            "{n} compactações. Barco de Teseu, com documentação pior.",
            "Você ainda sabe o que essa sessão pediu lá no começo?",
            "{n} vezes a janela encheu: pergunta menor é permitida.",
            "Quebra a tarefa e o contexto para de se comer.",
            "{n} reescritas da mesma memória, cada uma menor que a anterior.",
        ],
        "readRatio": [
            "{n}:1 de leitura por saída.",
            "Lendo uma biblioteca pra escrever um bilhete.",
            "Pra cada token escrito entram {n}, e o lado da leitura você paga em todo turno depois daquele em que o arquivo foi aberto.",
            "{n} tokens entram, um sai. Eficiente não é a palavra.",
            "Precisa do arquivo inteiro ou das quarenta linhas em volta do bug?",
            "Entrada é mais barata que saída por token, e é exatamente por isso que {n}:1 deixa de assustar e vira hábito.",
            "{n}:1 — boa parte desse contexto está só pegando carona.",
            "Aponta pra uma faixa em vez do arquivo inteiro.",
        ],
        "bashHeavy": [
            "{n}% das suas chamadas são Bash.",
            "As outras ferramentas estão bem ali.",
            "{n}% de tudo que você chamou hoje foi comando de shell, o que funciona até o dia em que um deles não é idempotente e a retentativa roda duas vezes.",
            "{n}% Bash. Existem outras ferramentas, dizem.",
            "O grep é mais rápido aqui ou só mais familiar?",
            "Comando de shell não tem schema, então nada confere ele antes de rodar.",
            "{n}% de shell: uma filosofia, de certo modo.",
            "Quando o martelo tem um pipe, tudo vira pipeline.",
        ],
        "cacheDrop": [
            "Cache em {n}%.",
            "Alguma coisa está invalidando o prefixo.",
            "O cache casa por prefixo exato, então um byte diferente lá na frente do prompt derruba tudo que vem depois, e o seu está em {n}%.",
            "{n}% de acerto. Um timestamp no system prompt faz exatamente isso.",
            "O que você colocou no topo do prompt hoje?",
            "Cache de prefixo é tudo ou nada por bloco: {n}% quer dizer que a maioria está sendo remontada.",
            "{n}% se paga em latência antes de se pagar em token.",
            "Move a parte volátil pro fim do prompt.",
        ],
        "nightOwl": [
            "Tá tarde.",
            "O commit vai continuar quebrado amanhã.",
            "Depois da meia-noite o bug que você persegue é typo mais vezes do que é race condition, e você é a pessoa errada pra notar a diferença.",
            "Tarde. Nada bom entra em produção a essa hora.",
            "Mais um e dorme?",
            "O você de amanhã lê esse código como estranho, e estranho não tem janela de contexto.",
            "O turno da madrugada escreve o código que o turno da manhã reverte.",
            "Vai dormir.",
        ],
        "sessionSpread": [
            "{n} sessões rodando.",
            "Alguém vai se perder nisso.",
            "São {n} sessões abertas ao mesmo tempo, cada uma segurando meia ideia que só você sabe diferenciar, incluindo o que quer que o {name} fosse.",
            "{n} de uma vez. Impressionante, ou um diagnóstico.",
            "Rápido: o que o {name} está fazendo agora?",
            "Trocar de contexto custa mais que a troca, porque custa a recarga.",
            "{n} Claudes, um você.",
            "Fecha as duas que você já esqueceu.",
        ],
        "quotaHigh": [
            "Janela de cinco horas em {n}%.",
            "Já foram {n}% da janela de cinco horas, e a janela não está nem aí pro que você ainda tinha planejado pra ela.",
            "Em {n}%, o quinto que sobra dá pra um turno longo e a leitura do que ele devolver.",
            "Quanto desses {n}% foi reler o mesmo arquivo?",
            "{n}% gastos. O último quinto sempre some mais rápido que o primeiro.",
            "Pergunta com critério daqui pra frente.",
            "Janela em {n}% não é aviso, é aritmética: o que sobrou é o que sobrou.",
            "{n}%, e o dia não acabou.",
        ],
        "quotaCritical": [
            "{n}% da janela da sessão.",
            "Termina o raciocínio.",
            "Em {n}%, o próximo turno longo é o que vai ser cortado no meio, e turno cortado gasta os tokens sem te deixar a resposta.",
            "{n}% queimados. Se estava guardando pra alguma coisa, é agora.",
            "Tem alguma coisa aqui que precisa acontecer dentro dessa janela?",
            "Não existe plano B dentro das mesmas cinco horas.",
            "{n}% usados, e nenhuma segunda janela pra assumir.",
            "Anota o estado em algum lugar que sobreviva a um restart.",
        ],
        "weeklyHigh": [
            "Janela semanal em {n}%.",
            "{n}% da semana já foram e o reset tem data, o que não é a mesma coisa que ter plano pros dias entre agora e ele.",
            "Sobram dias, cota não.",
            "{n}% gastos: o resto da semana roda no que ficou.",
            "{n}% da cota da semana. O calendário não negocia.",
            "Quais tarefas dessa semana precisavam mesmo do modelo grande?",
            "Teto semanal transforma toda terça movimentada numa sexta menor.",
            "Distribui, ou gasta e espera.",
        ],
        "limitSoon": [
            "{eta} de janela nesse ritmo.",
            "Nada que você começar agora está seguro.",
            "No ritmo atual o limite chega em {eta}, que é menos de um turno longo somado ao tempo de ler o que ele devolve.",
            "{eta} até o teto. Escolhe bem a próxima pergunta.",
            "Quer gastar os últimos {eta} nisso ou naquilo que você veio fazer?",
            "Anota onde você parou antes de a janela fechar.",
            "Estimativa feita pelo ritmo atual é uma reta desenhada por cima de uma curva torta.",
            "{eta} de cota, e depois vira relógio em vez de decisão.",
        ],
        "creditsLow": [
            "{v} de crédito extra sobrando.",
            "Depois disso, a resposta é não.",
            "O uso extra era o plano B e {v} é o que sobrou do plano B, então o próximo turno longo é o que gasta o fim dele.",
            "Crédito em {v}. O teto deixa de ser teórico.",
            "Você quer o resto de {v} indo pra isso ou pra amanhã?",
            "Confere o saldo antes de um turno longo, não durante.",
            "{v} é saldo, não ritmo — não diz nada sobre a velocidade com que está indo embora.",
            "O plano B tem {v} de plano B pela frente.",
        ],
        "incident": [
            "A Anthropic está reportando isto: {what}.",
            "Dessa vez não é o seu código.",
            "A página de status diz: {what}. Ou seja, aquele retry que você ia escrever já foi escrito por alguém do outro lado.",
            "Tentar de novo com raiva não conserta servidor dos outros.",
            "Quer ler alguma coisa enquanto isso passa?",
            "Incidente aberto: {what}.",
            "Erro de sobrecarga é o servidor dizendo que está cheio, não o cliente dizendo que está errado.",
            "É do lado deles, e o nome que deram foi: {what}.",
        ],
        "mcpAuth": [
            "{name} está esperando autorização.",
            "Até lá, é enfeite.",
            "O servidor MCP {name} está conectado mas não autorizado, então as ferramentas dele somem da lista e nada avisa que sumiram.",
            "{name} quer credencial. Está pedindo faz tempo, sem plateia.",
            "Você ainda usa o {name} ou ele só existe no config?",
            "Roda /mcp e dá o token pro {name}.",
            "Ferramenta que não está na lista é ferramenta que o modelo não lembra de usar.",
            "{name}: autorizado em lugar nenhum, listado em todo lugar.",
        ],
        "errorsClimbing": [
            "{n} erros de API em duas horas.",
            "As retentativas estão comendo os seus turnos.",
            "Foram {n} chamadas com falha nas últimas duas horas, e cada retentativa que esconde uma delas te cobra a espera duas vezes sem avisar.",
            "{n} erros e subindo. A retentativa esconde até parar de esconder.",
            "Está parecendo lento ou está parecendo quebrado?",
            "Backoff exponencial transforma pico em fila, e é por isso que nada parece errado.",
            "{n} erros desde a última calmaria, e nem todos são culpa sua.",
            "Para de culpar o prompt por {n} falhas de rede.",
        ],
        "opusFallback": [
            "Opus está em {n}% das chamadas de hoje.",
            "Confere as respostas duas vezes.",
            "A fatia de Opus caiu pra {n}% hoje contra uma semana bem mais pesada, o que costuma significar que alguém menor respondeu com a voz dele.",
            "{n}% de Opus hoje. Ninguém avisou da troca.",
            "Você trocou de modelo ou trocaram por você?",
            "Troca de modelo aparece no resultado antes de aparecer na configuração.",
            "{n}% de Opus: a mistura mudou e os prompts não.",
            "Vê qual modelo está respondendo antes de reescrever o prompt.",
        ],
        "slowResponses": [
            "Respostas em {n} segundos na média.",
            "Tempo suficiente pra perder o fio.",
            "Ida e volta de {n} segundos é longo o bastante pra você começar outra coisa, e o que isso custa é o contexto da sua cabeça, não o da janela.",
            "{n} segundos por turno. Isso não é o modelo pensando melhor.",
            "Tem o que ler enquanto isso volta?",
            "Latência se mede por chamada; a espera que você sente é por turno, e turno é várias chamadas.",
            "{n} segundos cada, e a média está escondendo as piores.",
            "{n}s de ida e volta. Paciência virou dependência.",
        ],
        "expensiveSession": [
            "{name} é ${usd} do dia de hoje.",
            "Um repositório, quase toda a conta.",
            "O {name} responde por ${usd} hoje, mais da metade de tudo, então seja lá o que ele estava fazendo, estava fazendo a preço cheio.",
            "${usd} no {name}. Tomara que fosse estrutural.",
            "O {name} valeu ${usd} pra você ou só pro loop?",
            "Custo se concentra onde o contexto é maior, não onde o trabalho é mais difícil.",
            "{name}: ${usd}, e o dia não acabou.",
            "Divide a sessão longa antes que ela divida o orçamento.",
        ],
        "runwayShort": [
            "Sobram {h}h de crédito nesse ritmo.",
            "Depois disso a decisão não é mais sua.",
            "A projeção divide o que sobrou pelo que você gastou por hora, então {h}h é uma reta passada por cima de uma tarde bem irregular.",
            "{h}h de autonomia. O ritmo é a parte que ainda dá pra mudar.",
            "Você prefere ficar sem crédito antes ou depois do jantar?",
            "Gastar mais rápido não estica {h}h.",
            "{h}h, e uma fila de turnos longos é o jeito mais rápido de virar menos.",
            "Autonomia é saldo dividido por ritmo: metade do ritmo, o dobro do tempo.",
        ],
        "recordSession": [
            "{h}h em uma sessão só.",
            "Perto do seu recorde.",
            "Essa sessão está aberta há {h} horas, tempo suficiente pro começo dela já ter sido compactado pra fora do meio.",
            "{h}h e ainda aberta. Contexto tem meia-vida.",
            "Você lembra o que a primeira mensagem dessa sessão pediu?",
            "Recorde assim mede a sessão, não o trabalho.",
            "Sessão longa não acumula entendimento, acumula resumo.",
            "Abre uma nova e cola as três coisas que importam.",
        ],
        "branchOpinion": [
            "{name} está na {branch}.",
            "Branch é barato; essa aí não.",
            "Você está commitando direto na {branch} em {name}, onde todo commit já é de todo mundo e o desfazer é um revert com o seu nome nele.",
            "{branch} em {name}. Ousado, no sentido histórico.",
            "Você aprovaria esse diff se outra pessoa tivesse empurrado ele na {branch}?",
            "Branch é um nome pra um commit, e criar uma custa um ponteiro.",
            "{name} na {branch}, sem caminho barato de volta.",
            "Cria a branch primeiro, depois seja corajoso.",
        ],
        "streakDay": [
            "{n} dias seguidos.",
            "O log percebeu antes de você.",
            "São {n} dias consecutivos com alguma coisa registrada, o que fala mais do hábito do que de qualquer um dos dias lá dentro.",
            "Dia {n}. Ninguém está contando, fora o log.",
            "Isso é uma sequência ou uma escala que você não combinou?",
            "Sequência acaba no dia em que você começa a defender ela.",
            "{n} dias sem falhar, e o contador não tem opinião sobre o código.",
            "Tira um dia e vê se sobrevive.",
        ],
        "offPeak": [
            "Esse horário não é seu.",
            "Seu próprio histórico diz que você costuma estar em outro lugar agora.",
            "Essa hora está fora do bloco que o seu log chama de dia de trabalho, e é de hora incomum que sai o commit que ninguém lembra de ter escrito.",
            "Hora estranha pra você. Alguma coisa não esperou.",
            "Isso precisava ser agora?",
            "O histograma das suas últimas semanas não tem barra nenhuma aqui.",
            "Fora do seu horário, pelos seus dados e não pela minha opinião.",
            "Seja lá o que for, continua aqui às dez.",
        ],
        "ambient": [
            "Tudo quieto.",
            "Ninguém precisa de você, e isso é um estado que vale notar enquanto dura.",
            "Nenhum alerta, nenhuma pergunta, nada no vermelho — o painel inteiro está sem graça e eu conferi duas vezes.",
            "Tudo certo. Suspeitamente certo.",
            "Aproveitando a calmaria ou procurando o que quebrar?",
            "Nada a relatar.",
            "Máquinas comportadas. Profundamente sem graça.",
            "Ainda aqui, ainda olhando, ainda nada.",
        ],
        "philosophy": [
            "Você é a parte mais lenta desse loop e a única que decide alguma coisa.",
            "Ler código é mais difícil que escrever, e é por isso que se reescreve tanta coisa em vez de ler.",
            "Vai terminar. Se termina o que você quis dizer é outra pergunta.",
            "Espera de quatro segundos é uma pausa; de quarenta, é troca de contexto.",
            "Todo prompt é um palpite sobre quais quarenta linhas do repositório importam, e quase todo o custo está em chutar largo.",
            "Automatizar o trabalho não tira ele. Move você de fazer pra revisar.",
            "Ninguém mede atenção.",
            "O caro nunca foi a resposta, é decidir se a resposta está certa.",
        ],
    },
}
